apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: applications
  namespace: argocd
spec:
  destination:
    name: aksmain-eastus-dev
  project: default
  source:
    path: apps
    repoURL: https://github.com/urbinaalex17/argocd-with-akuity # Update to your repo URL.
    targetRevision: HEAD
