apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/urbinaalex17/argocd-with-akuity' # Update to match your fork.
    path: guestbook
    targetRevision: HEAD
  destination:
    namespace: guestbook
    name: aksmain-eastus-dev # Update this value.
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
